# Global Relayer configuration
global:
  privateKey: ''                        # The privateKey of the account that will be submitting the packet relays
  logLevel: 'info'

  monitor:
    interval: 5000                      # Interval at which to poll the chains RPCs for new blocks
    blockDelay: 1                       # Delay with which to process the chain blocks

  getter:
    retryInterval: 5000                 # Time to wait before retrying a failed query
    maxBlocks: 1000                     # Maximum number of blocks to query in a single call

  submitter:
    enabled: true
    newOrdersDelay: 1000                # Time to wait before processing new 'submission' orders
    retryInterval: 30000                # Time to wait before retrying a failed transaction
    maxTries: 3                         # Maximum tries for a transaction
    maxPendingTransactions: 50          # Maximum number of transactions within the 'submit' pipeline.
    evaluationRetryInterval: 3600000    # Interval at which to reevaluate whether to relay a message.
    maxEvaluationDuration: 86400000     # Time after which to drop an undelivered message.

  evaluator:
    verificationDeliveryGas: '55000'    # Gas amount used for packet verification upon delivery.
    unrewardedDeliveryGas: '25000'      # Gas amount that will be unrewarded on delivery submission.
    minDeliveryReward: 0.001            # In the 'pricingDenomination' specified below
    relativeMinDeliveryReward: 0.001
    verificationAckGas: '55000'         # Gas amount used for packet verification upon ack.
    unrewardedAckGas: '25000'           # Gas amount that will be unrewarded on ack submission.
    minAckReward: 0.001                 # In the 'pricingDenomination' specified below
    relativeMinAckReward: 0.001
    profitabilityFactor: 1.0            # Profitiability evaluation adjustment factor. A larger
                                        # factor implies a larger profitability guarantee.

  pricing:
    provider: 'coin-gecko'
    coinDecimals: 18
    pricingDenomination: 'usd'


  wallet:
    retryInterval: 30000                # Time to wait before retrying a failed transaction
    maxTries: 3                         # Maximum tries for a transaction
    maxPendingTransactions: 50          # Maximum number of transactions within the 'submit' pipeline
    confirmations: 1                    # Number of confirmations to wait before accepting a transaction as 'completed'.
    confirmationTimeout: 90000          # Timeout for a transaction to confirm

    lowGasBalanceWarning:               # Gas balance below which a 'low balance' warning is emitted.
      '1000000000000000000'
    gasBalanceUpdateInterval: 50        # Number of transactions after which to update the Underwriter gas balance from the rpc. 

    # EIP-1559 Transactions
    maxFeePerGas: '200000000000'        # 'maxFeePerGas' set for all transactions (for chains that support eip-1559)

    maxAllowedPriorityFeePerGas:        # Upper bound to the 'maxPriorityFeePerGas' set on transactions (for chains that support eip-1559)
      '100000000000'
    maxPriorityFeeAdjustmentFactor:     # Decimal factor used to adjust the 'maxPriorityFeePerGas' returned by 'getFeeData()'. 
      1.01                              # The resulting value is set as the 'maxPriorityFeePerGas' property of the transaction
                                        # if it is smaller than the configuration property 'maxAllowedPriorityFeePerGas' (if set).

    # Legacy Transactions
    maxAllowedGasPrice: '200000000000'  # Upper bound to the 'gasPrice' set on transactions (for chains that do not support eip-1559)
    gasPriceAdjustmentFactor: 1.01      # Decimal factor used to adjust the 'gasPrice' returned by 'getFeeData()'. The resulting 
                                        # value is set as the 'gasPrice' property of the transaction if it is smaller than the 
                                        # configuration property 'maxAllowedGasPrice' (if set).

    # All Transactions
    priorityAdjustmentFactor: 1.05      # Decimal factor used to adjust **all** the gas prices (including 'maxFeePerGas') for 
                                        # priority transactions.

  persister:
    enabled: false
    postgresString: 'postgresql://username:password@location/database?sslmode=require'

# AMBs configuration
ambs:
  # Mock is used for internal testnets. For production it should never be used.
  - name: mock
    enabled: false                      # Defaults to 'true' if the key is missing
    incentivesAddress: '0x0000000000000000000000000000000000000000'
    privateKey: ''

  # While we can't relay packages for Polymer, we to still collect the packages for the underwriter to work.
  - name: polymer

  - name: wormhole
    isTestnet: true

  - name: layer-zero
    packetCost: '6000000000000'

# Chain configuration
chains:
  - chainId: 11155111
    name: 'Sepolia'
    rpc: 'https://eth-sepolia-public.unifra.io'

    # startingBlock   # The block number at which to start Relaying (not all AMB collectors may support this property)
    # stoppingBlock   # The block number at which to stop Relaying (not all AMB collectors may support this property)

    # Overrides
    monitor:
      blockDelay: 2
      interval: 5000

    pricing:
      gasCoinId: 'ethereum'  # coin-gecko pricing provider specific configuration

    # AMB configuration
    wormhole:
      wormholeChainId: 10002
      incentivesAddress: '0x294F41D30D058C9e5A71810A6C758E595b7aC170'
      bridgeAddress: '0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78'

  - chainId: 11155420
    name: 'OP Sepolia'
    rpc: 'https://sepolia.optimism.io'
    resolver: 'op-sepolia'
    pricing:
      gasCoinId: 'ethereum'  # coin-gecko pricing provider specific configuration
    wormhole:
      wormholeChainId: 10005
      incentivesAddress: '0x198cDD55d90277726f3222D5A8111AdB8b0af9ee'
      bridgeAddress: '0x31377888146f3253211EFEf5c676D41ECe7D58Fe'
    layer-zero:
      layerZeroChainId: 40232
      incentivesAddress: '0xd41ace766aed57fefdca3a7d27d20b837284b872'
      bridgeAddress: '0x6edce65403992e310a62460808c4b910d972f10f'
      receiverAddress: '0x9284fd59B95b9143AF0b9795CAC16eb3C723C9Ca'

  - chainId: 84532
    name: 'Base Sepolia'
    rpc: 'https://sepolia.base.org'
    resolver: 'base-sepolia'
    pricing:
      gasCoinId: 'ethereum'  # coin-gecko pricing provider specific configuration
    wormhole:
      wormholeChainId: 10004
      incentivesAddress: '0x63B4E24DC9814fAcDe241fB4dEFcA04d5fc6d763'
      bridgeAddress: '0x79A1027a6A159502049F10906D333EC57E95F083'

  - chainId: 168587773
    name: 'Blast Testnet'
    rpc: 'https://sepolia.blast.io'
    pricing:
      gasCoinId: 'ethereum'  # coin-gecko pricing provider specific configuration
    wormhole:
      wormholeChainId: 36
      incentivesAddress: '0x9524ACA1fF46fAd177160F0a803189Cb552A3780'
      bridgeAddress: '0x473e002D7add6fB67a4964F13bFd61280Ca46886'

  - chainId: 421614
    name: "Arbitrum Sepolia"
    rpc: "https://arbitrum-sepolia-rpc.publicnode.com"
    resolver: 'arbitrum'
    pricing:
      coinId: 'ethereum'  # coin-gecko pricing provider specific configuration
    monitor:
      blockDelay: 5
      interval: 2000
    getter:
      maxBlocks: 5000
    wormhole:
      wormholeChainId: 10003
      incentivesAddress: "0x59aa9e2339dd0c019f188f1ed9b27b9a10ae664d"
      bridgeAddress: "0x6b9C8671cdDC8dEab9c719bB87cBd3e782bA6a35"
    layer-zero:
      layerZeroChainId: 40231
      incentivesAddress: '0xd41ace766aed57fefdca3a7d27d20b837284b872'
      bridgeAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'
      receiverAddress: '0x75Db67CDab2824970131D5aa9CECfC9F69c69636'

  - chainId: 713715
    name: 'Sei Devnet'
    rpc: 'https://evm-rpc-arctic-1.sei-apis.com'
    pricing:
      coinId: 'sei-network'  # coin-gecko pricing provider specific configuration
    monitor:
      interval: 2000
      blockDelay: 10
    layer-zero:
      layerZeroChainId: 40258
      incentivesAddress: '0xd41ace766aed57fefdca3a7d27d20b837284b872'
      bridgeAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'
      receiverAddress: '0xcF1B0F4106B0324F96fEfcC31bA9498caa80701C'
      packetCost: '100000000000000000'
