# Global Relayer configuration
global:
  privateKey: ''                        # The privateKey of the account that will be submitting the packet relays
  logLevel: 'info'

  monitor:
    interval: 5000                      # Interval at which to poll the chains RPCs for new blocks
    blockDelay: 1                       # Delay with which to process the chain blocks

  getter:
    retryInterval: 5000                 # Time to wait before retrying a failed query
    maxBlocks: 1000                     # Maximum number of blocks to query in a single call

  submitter:
    enabled: true
    newOrdersDelay: 1000                # Time to wait before processing new 'submission' orders
    retryInterval: 30000                # Time to wait before retrying a failed transaction
    maxTries: 3                         # Maximum tries for a transaction
    maxPendingTransactions: 50          # Maximum number of transactions within the 'submit' pipeline.

    # Gas properties
    gasLimitBuffer:                     # Extra gasLimit buffer. Customizable per AMB.
      default: 10000
      mock: 50000

  wallet:
    retryInterval: 30000                # Time to wait before retrying a failed transaction
    maxTries: 3                         # Maximum tries for a transaction
    maxPendingTransactions: 50          # Maximum number of transactions within the 'submit' pipeline
    confirmations: 1                    # Number of confirmations to wait before accepting a transaction as 'completed'.
    confirmationTimeout: 90000          # Timeout for a transaction to confirm

    lowGasBalanceWarning:               # Gas balance below which a 'low balance' warning is emitted.
      '1000000000000000000'
    gasBalanceUpdateInterval: 50        # Number of transactions after which to update the Underwriter gas balance from the rpc. 

    # EIP-1559 Transactions
    maxFeePerGas: '10000000000'        # 'maxFeePerGas' set for all transactions (for chains that support eip-1559)

    maxAllowedPriorityFeePerGas:        # Upper bound to the 'maxPriorityFeePerGas' set on transactions (for chains that support eip-1559)
      '5000000000'
    maxPriorityFeeAdjustmentFactor:     # Decimal factor used to adjust the 'maxPriorityFeePerGas' returned by 'getFeeData()'. 
      1.01                              # The resulting value is set as the 'maxPriorityFeePerGas' property of the transaction
                                        # if it is smaller than the configuration property 'maxAllowedPriorityFeePerGas' (if set).

    # Legacy Transactions
    maxAllowedGasPrice: '10000000000'  # Upper bound to the 'gasPrice' set on transactions (for chains that do not support eip-1559)
    gasPriceAdjustmentFactor: 1.01      # Decimal factor used to adjust the 'gasPrice' returned by 'getFeeData()'. The resulting 
                                        # value is set as the 'gasPrice' property of the transaction if it is smaller than the 
                                        # configuration property 'maxAllowedGasPrice' (if set).

    # All Transactions
    priorityAdjustmentFactor: 1.05      # Decimal factor used to adjust **all** the gas prices (including 'maxFeePerGas') for 
                                        # priority transactions.

  persister:
    enabled: false
    postgresString: 'postgresql://username:password@location/database?sslmode=require'

# AMBs configuration
ambs:
  - name: wormhole
    isTestnet: false

  - name: layerZero
    isTestnet: true 

# Chain configuration
chains:
  - chainId: 10
    name: 'OP Mainnet'
    rpc: 'https://mainnet.optimism.io'

    # startingBlock   # The block number at which to start Relaying (not all AMB collectors may support this property)
    # stoppingBlock   # The block number at which to stop Relaying (not all AMB collectors may support this property)

    # Overrides
    monitor:
      interval: 1000

    # AMB configuration
    wormhole:
      wormholeChainId: 24
      incentivesAddress: '0x8C8727276725b7Da11fDA6e2646B2d2448E5B3c5'
      bridgeAddress: '0xEe91C335eab126dF5fDB3797EA9d6aD93aeC9722'
    layerZero:
      bridgeAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'
      incentivesAddress: '0xDb93559e30F5A3845438DDcf7Ca8A2D6D9005d30'
      recieverAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'


  - chainId: 81457
    name: 'Blast Mainnet'
    rpc: 'https://rpc.blast.io'
    monitor:
      interval: 1000
    wormhole:
      wormholeChainId: 36
      incentivesAddress: '0x3C5C5436BCa59042cBC835276E51428781366d85'
      bridgeAddress: '0xbebdb6C8ddC678FfA9f8748f85C815C556Dd8ac6'
    layerZero:
      bridgeAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'
      incentivesAddress: '0xDb93559e30F5A3845438DDcf7Ca8A2D6D9005d30'
      recieverAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'


  
  - chainId: 8453
    name: 'Base Mainnet'
    rpc: 'https://mainnet.base.org'
    monitor:
      interval: 1000
    wormhole:
      wormholeChainId: 30
      incentivesAddress: '0x3C5C5436BCa59042cBC835276E51428781366d85'
      bridgeAddress: '0xbebdb6C8ddC678FfA9f8748f85C815C556Dd8ac6'
    layerZero:
      bridgeAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'
      incentivesAddress: '0xDb93559e30F5A3845438DDcf7Ca8A2D6D9005d30'
      recieverAddress: '0x6EDCE65403992e310A62460808c4b910D972f10f'


